/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PostIdRouteImport } from './routes/$postId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIdIndexRouteImport } from './routes/$postId/index'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdIndexRoute = PostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$postId': typeof PostIdRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/$postId/': typeof PostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/$postId': typeof PostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$postId': typeof PostIdRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/$postId/': typeof PostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$postId' | '/dashboard' | '/new' | '/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/new' | '/$postId'
  id: '__root__' | '/' | '/$postId' | '/dashboard' | '/new' | '/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostIdRoute: typeof PostIdRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$postId': {
      id: '/$postId'
      path: '/$postId'
      fullPath: '/$postId'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$postId/': {
      id: '/$postId/'
      path: '/'
      fullPath: '/$postId/'
      preLoaderRoute: typeof PostIdIndexRouteImport
      parentRoute: typeof PostIdRoute
    }
  }
}

interface PostIdRouteChildren {
  PostIdIndexRoute: typeof PostIdIndexRoute
}

const PostIdRouteChildren: PostIdRouteChildren = {
  PostIdIndexRoute: PostIdIndexRoute,
}

const PostIdRouteWithChildren =
  PostIdRoute._addFileChildren(PostIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostIdRoute: PostIdRouteWithChildren,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
